// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDIHdQJ534Bb4SFi4GhdKckDvVOox2T7Do',
    appId: '1:637343477600:android:86aefdf7ab43b8bc187805',
    messagingSenderId: '637343477600',
    projectId: 'my-adas-app',
    storageBucket: 'my-adas-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCxk1zbk23fzOvKGAOkSjDM44nuXy6hY_E',
    appId: '1:637343477600:ios:96a6c9656ea77c00187805',
    messagingSenderId: '637343477600',
    projectId: 'my-adas-app',
    storageBucket: 'my-adas-app.appspot.com',
    androidClientId: '637343477600-9qtp660p8jhn5em9ls7eed6iikqdfpnc.apps.googleusercontent.com',
    iosClientId: '637343477600-82bukk9jo5mmlj6up23gvnj467gmr2sg.apps.googleusercontent.com',
    iosBundleId: 'com.adasdevelopment.app',
  );
}
